FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Construire l'app pour production
RUN npm run build

# Installer le serveur "serve"
RUN npm install -g serve

# Exposer le port
EXPOSE 3000

# Servir l'app
CMD ["serve", "-s", "build", "-l", "3000"]
