apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '@gmail.com'
      smtp_auth_username: '@gmail.com'
      smtp_auth_password: ''
      smtp_require_tls: true
    route:
      receiver: 'email-notifications'
      group_wait: 10s
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: '@gmail.com'
            send_resolved: true