# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mern-tasks-tls
spec:
  secretName: mern-tasks-tls
  duration: 8760h  # 1 an
  renewBefore: 720h # 30 jours avant expiration
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: mern-tasks.com
  dnsNames:
    - mern-tasks.com
