apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  #mongo-user: bm91aGFpbGE=
  #mongo-password: bm91aGExMjM=
  #MONGO_URI: bW9uZ29kYitzcnY6Ly9ub3VoYWlsYTpub3VoYTEyM0BjbHVzdGVyMC5xcXVzZC5tb25nb2RiLm5ldC9LOD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=